sudo: false
language: ruby
rvm:
  - 2.4.2
before_install:
  - gem install bundler
  - export TZ=Australia/Melbourne
  - env
bundler_args: --without development
dist: trusty
cache:
  bundler: true
  apt: true
  directories:
  - "$TRAVIS_BUILD_DIR/dependencies"
env:
  global:
    - RAILS_ENV=test
script:
  - bundle exec rspec spec
addons:
  ssh_known_hosts: git.trikeapps.com
after_failure:
  - ./config/ci/travis/blamebot.sh
